import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Google Auth Example */}
        <div
          style={{
            marginTop: 32,
            marginBottom: 32,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          {session ? (
            <>
              <p>Welcome, {session.user.name}!</p>
              {session.user.image && (
                <img
                  src={session.user.image}
                  alt="User avatar"
                  style={{ width: 48, borderRadius: "50%" }}
                />
              )}
              <button onClick={() => signOut()}>Sign out</button>
            </>
          ) : (
            <button
              onClick={() => signIn("google")}
              style={{
                display: "flex",
                alignItems: "center",
                padding: "10px 20px",
                backgroundColor: "#4285F4",
                color: "white",
                border: "none",
                borderRadius: "4px",
                cursor: "pointer",
                fontSize: "16px",
                fontWeight: "bold",
              }}
            >
              <img
                src="https://www.google.com/favicon.ico"
                alt="Google"
                style={{ marginRight: "10px", width: "20px", height: "20px" }}
              />
              Sign in with Google
            </button>
          )}
        </div>
      </main>
    </>
  );
}
